using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;

namespace FrontEnd.Modelos_fe
{
    public class paises
    {
        public Dictionary<string,string> Codpaises()
        {
            Dictionary<string,string> pais = new Dictionary<string,string>();

            pais.Add("AFG", "Afganistán");
            pais.Add("ALB", "Albania");
            pais.Add("DEU", "Alemania");
            pais.Add("AND", "Andorra");
            pais.Add("AGO", "Angola");
            pais.Add("AIA", "Anguila");
            pais.Add("ATA", "Antártida");
            pais.Add("ATG", "Antigua y Barbuda");
            pais.Add("SAU", "Arabia Saudita");
            pais.Add("DZA", "Argelia");
            pais.Add("ARG", "Argentina");
            pais.Add("ARM", "Armenia");
            pais.Add("ABW", "Aruba");
            pais.Add("AUS", "Australia");
            pais.Add("AUT", "Austria");
            pais.Add("AZE", "Azerbaiyán");
            pais.Add("BHS", "Bahamas");
            pais.Add("BHR", "Bahrein");
            pais.Add("GGY", "Bailía de Guernsey");
            pais.Add("BGD", "Bangladesh");
            pais.Add("BRB", "Barbados");
            pais.Add("BLR", "Belarús");
            pais.Add("BEL", "Bélgica");
            pais.Add("BLZ", "Belice");
            pais.Add("BEN", "Benín");
            pais.Add("BMU", "Bermudas");
            pais.Add("BOL", "Bolivia");
            pais.Add("BES", "Bonaire, San Eustaquio y Saba");
            pais.Add("BIH", "Bosnia y Hercegovina");
            pais.Add("BWA", "Botsuana");
            pais.Add("BRA", "Brasil");
            pais.Add("BRN", "Brunéi");
            pais.Add("BGR", "Bulgaria");
            pais.Add("BFA", "Burkina Faso");
            pais.Add("BDI", "Burundi");
            pais.Add("BTN", "Bután");
            pais.Add("CPV", "Cabo Verde");
            pais.Add("KHM", "Cambodia");
            pais.Add("CMR", "Camerún");
            pais.Add("CAN", "Canadá");
            pais.Add("QAT", "Catar");
            pais.Add("TCD", "Chad");
            pais.Add("CZE", "Chequia");
            pais.Add("CHL", "Chile");
            pais.Add("CHN", "China");
            pais.Add("CYP", "Chipre");
            pais.Add("VAT", "Ciudad del Vaticano");
            pais.Add("COL", "Colombia");
            pais.Add("COM", "Comores");
            pais.Add("COG", "Congo");
            pais.Add("PRK", "Corea del Norte");
            pais.Add("KOR", "Corea del Sur");
            pais.Add("CIV", "Costa de Marfil");
            pais.Add("CRI", "Costa Rica");
            pais.Add("HRV", "Croacia");
            pais.Add("CUB", "Cuba");
            pais.Add("CUW", "Curaçao");
            pais.Add("DNK", "Dinamarca");
            pais.Add("DMA", "Dominica");
            pais.Add("ECU", "Ecuador");
            pais.Add("EGY", "Egipto");
            pais.Add("SLV", "El Salvador");
            pais.Add("ARE", "Emiratos Árabes Unidos");
            pais.Add("ERI", "Eritrea");
            pais.Add("SVK", "Eslovaquia");
            pais.Add("SVN", "Eslovenia");
            pais.Add("ESP", "España");
            pais.Add("FSM", "Estados Federados de Micronesia");
            pais.Add("USA", "Estados Unidos");
            pais.Add("EST", "Estonia");
            pais.Add("SWZ", "Esuatini");
            pais.Add("ETH", "Etiopía");
            pais.Add("FJI", "Fiji");
            pais.Add("PHL", "Filipinas");
            pais.Add("FIN", "Finlandia");
            pais.Add("FRA", "Francia");
            pais.Add("GAB", "Gabón");
            pais.Add("GMB", "Gambia");
            pais.Add("GEO", "Georgia");
            pais.Add("SGS", "Georgia del Sur y las Islas Sandwich del Sur");
            pais.Add("GHA", "Ghana");
            pais.Add("GIB", "Gibraltar");
            pais.Add("GRD", "Granada");
            pais.Add("GRC", "Grecia");
            pais.Add("GRL", "Groenlandia");
            pais.Add("GLP", "Guadalupe");
            pais.Add("GUM", "Guam");
            pais.Add("GTM", "Guatemala");
            pais.Add("GUY", "Guayana");
            pais.Add("GUF", "Guayana Francesa");
            pais.Add("GIN", "Guinea");
            pais.Add("GNQ", "Guinea Ecuatorial");
            pais.Add("GNB", "Guinea-Bissau");
            pais.Add("HTI", "Haití");
            pais.Add("HND", "Honduras");
            pais.Add("HKG", "Hong Kong");
            pais.Add("HUN", "Hungría");
            pais.Add("IND", "India");
            pais.Add("IDN", "Indonesia");
            pais.Add("IRN", "Irán");
            pais.Add("IRQ", "Iraq");
            pais.Add("IRL", "Irlanda");
            pais.Add("BVT", "Isla Bouvet");
            pais.Add("IMN", "Isla de Man");
            pais.Add("CXR", "Isla de Navidad");
            pais.Add("MAF", "Isla de San Martín");
            pais.Add("MUS", "Isla Mauricio");
            pais.Add("NFK", "Isla Norfolk");
            pais.Add("ISL", "Islandia");
            pais.Add("ALA", "Islas Åland");
            pais.Add("CYM", "Islas Caimán");
            pais.Add("CCK", "Islas Cocos");
            pais.Add("COK", "Islas Cook");
            pais.Add("FRO", "Islas Feroe");
            pais.Add("HMD", "Islas Heard y McDonald");
            pais.Add("FLK", "Islas Malvinas");
            pais.Add("MNP", "Islas Marianas del Norte");
            pais.Add("MHL", "Islas Marshall");
            pais.Add("PCN", "Islas Pitcairn");
            pais.Add("SLB", "Islas Salomón");
            pais.Add("TCA", "Islas Turcas y Caicos");
            pais.Add("VGB", "Islas Vírgenes (UK)");
            pais.Add("VIR", "Islas Vírgenes Americanas");
            pais.Add("ISR", "Israel");
            pais.Add("ITA", "Italia");
            pais.Add("JAM", "Jamaica");
            pais.Add("JPN", "Japón");
            pais.Add("JEY", "Jersey");
            pais.Add("JOR", "Jordania");
            pais.Add("KAZ", "Kazajstán");
            pais.Add("KEN", "Kenia");
            pais.Add("KGZ", "Kirguistán");
            pais.Add("KIR", "Kiribati");
            pais.Add("XKX", "Kosovo");
            pais.Add("KWT", "Kuwait");
            pais.Add("LAO", "Laos");
            pais.Add("LSO", "Lesotho");
            pais.Add("LVA", "Letonia");
            pais.Add("LBN", "Líbano");
            pais.Add("LBR", "Liberia");
            pais.Add("LBY", "Libia");
            pais.Add("LIE", "Liechtenstein");
            pais.Add("LTU", "Lituania");
            pais.Add("LUX", "Luxemburgo");
            pais.Add("MAC", "Macao");
            pais.Add("MKD", "Macedonia del Norte");
            pais.Add("MDG", "Madagascar");
            pais.Add("MYS", "Malasia");
            pais.Add("MWI", "Malaui");
            pais.Add("MDV", "Maldivas");
            pais.Add("MLI", "Malí");
            pais.Add("MLT", "Malta");
            pais.Add("MAR", "Marruecos");
            pais.Add("MTQ", "Martinica");
            pais.Add("MRT", "Mauritania");
            pais.Add("MYT", "Mayotte");
            pais.Add("MEX", "México");
            pais.Add("MDA", "Moldavia");
            pais.Add("MNG", "Mongolia");
            pais.Add("MNE", "Montenegro");
            pais.Add("MSR", "Montserrat");
            pais.Add("MOZ", "Mozambique");
            pais.Add("MMR", "Myanmar");
            pais.Add("NAM", "Namibia");
            pais.Add("NRU", "Nauru");
            pais.Add("NPL", "Nepal");
            pais.Add("NIC", "Nicaragua");
            pais.Add("NER", "Níger");
            pais.Add("NGA", "Nigeria");
            pais.Add("NIU", "Niue");
            pais.Add("NOR", "Noruega");
            pais.Add("NCL", "Nueva Caledonia");
            pais.Add("NZL", "Nueva Zelandia");
            pais.Add("OMN", "Omán");
            pais.Add("NLD", "Países Bajos");
            pais.Add("PAK", "Pakistán");
            pais.Add("PLW", "Palaos");
            pais.Add("PSE", "Palestina");
            pais.Add("PAN", "Panamá");
            pais.Add("PNG", "Papúa Nueva Guinea");
            pais.Add("PRY", "Paraguay");
            pais.Add("PER", "Perú");
            pais.Add("PYF", "Polinesia Francesa");
            pais.Add("POL", "Polonia");
            pais.Add("PRT", "Portugal");
            pais.Add("MCO", "Principado de Mónaco");
            pais.Add("PRI", "Puerto Rico");
            pais.Add("GBR", "Reino Unido");
            pais.Add("CAF", "República Centroafricana");
            pais.Add("COD", "República Democrática del Congo");
            pais.Add("DOM", "República Dominicana");
            pais.Add("REU", "Reunión");
            pais.Add("RWA", "Ruanda");
            pais.Add("ROU", "Rumania");
            pais.Add("RUS", "Rusia");
            pais.Add("ESH", "Sáhara Occidental");
            pais.Add("WSM", "Samoa");
            pais.Add("ASM", "Samoa Americana");
            pais.Add("BLM", "San Bartolomé");
            pais.Add("KNA", "San Cristóbal y Nieves");
            pais.Add("SMR", "San Marino");
            pais.Add("SPM", "San Pedro y Miquelón");
            pais.Add("VCT", "San Vicente y las Granadinas");
            pais.Add("SHN", "Santa Elena, Ascensión y Tristán de Acuña");
            pais.Add("LCA", "Santa Lucía");
            pais.Add("STP", "Santo Tomé y Príncipe");
            pais.Add("SEN", "Senegal");
            pais.Add("SRB", "Serbia");
            pais.Add("SYC", "Seychelles");
            pais.Add("SLE", "Sierra Leona");
            pais.Add("SGP", "Singapur");
            pais.Add("SXM", "Sint Maarten");
            pais.Add("SYR", "Siria");
            pais.Add("SOM", "Somalia");
            pais.Add("LKA", "Sri Lanka");
            pais.Add("ZAF", "Sudáfrica");
            pais.Add("SDN", "Sudán");
            pais.Add("SSD", "Sudán del Sur");
            pais.Add("SWE", "Suecia");
            pais.Add("CHE", "Suiza");
            pais.Add("SUR", "Surinam");
            pais.Add("SJM", "Svalbard y Jan Mayen");
            pais.Add("THA", "Tailandia");
            pais.Add("TWN", "Taiwán");
            pais.Add("TZA", "Tanzania");
            pais.Add("TJK", "Tayikistán");
            pais.Add("IOT", "Territorio Británico del Océano Índico");
            pais.Add("ATF", "Territorios Australes y Antárticos Franceses");
            pais.Add("TLS", "Timor Oriental");
            pais.Add("TGO", "Togo");
            pais.Add("TKL", "Tokelau");
            pais.Add("TON", "Tonga");
            pais.Add("TTO", "Trinidad y Tobago");
            pais.Add("TUN", "Túnez");
            pais.Add("TKM", "Turkmenistán");
            pais.Add("TUR", "Turquía");
            pais.Add("TUV", "Tuvalu");
            pais.Add("UKR", "Ucrania");
            pais.Add("UGA", "Uganda");
            pais.Add("URY", "Uruguay");
            pais.Add("UZB", "Uzbekistán");
            pais.Add("VUT", "Vanuatu");
            pais.Add("VEN", "Venezuela");
            pais.Add("VNM", "Vietnam");
            pais.Add("WLF", "Wallis y Futuna");
            pais.Add("YEM", "Yemen");
            pais.Add("DJI", "Yibuti");
            pais.Add("ZMB", "Zambia");
            pais.Add("ZWE", "Zimbabue");


            return pais;

        }
    }
}